
# This file was *autogenerated* from the file exp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_22 = Integer(22); _sage_const_2 = Integer(2); _sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
import ast
q = 1461501637330902918203684832716283019655932542983L
d = _sage_const_22 
l = _sage_const_9 
bound = q / (_sage_const_2  ** (l+_sage_const_1 ))

data = open('data').read()
data=data.split('\n')
t,u = map(ast.literal_eval,data)

m = []
for i in range(d):
    tmp = [_sage_const_0 ] * (d+_sage_const_2 )
    tmp[i] = q
    m.append(tmp)
m.append(t+[_sage_const_1 /(_sage_const_2 **(l+_sage_const_1 )), _sage_const_0 ])
m.append(u+[_sage_const_0 , bound])

ma = matrix(QQ, m)
mb = ma.LLL()

num = -mb[_sage_const_1 ][-_sage_const_2 ] * (_sage_const_2 **(l+_sage_const_1 ))
if num<_sage_const_0 :
    num = num+q
print num

